### PR TITLE
Add support for wireguard interface

### LINKED ISSUE #133: Add support for wireguard interface
##### SUMMARY
Add support for parsing wireguard interface like wg01 in vyos.vyos.vyos_interfaces parameter name

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vyos.vyos.vyos_interfaces

##### ADDITIONAL INFORMATION
Better and much easier managing wireguard interfaces, state option using vyos_interfaces.
The main problem with using vyos.vyos.vyos_config is missing the state option and it's needed to make advanced when conditions for setup peers. Also, vyos_config is every time in the changed state
 
```yaml
FROM
- name: Setup wireguard interface wg01
  vyos.vyos.vyos_config:
    lines:
    - set interfaces wireguard wg01 description WGTunnel
    - set interfaces wireguard wg01 port 51820
    - set interfaces wireguard wg01 address 172.31.0.1/24
    
- name: Adding wireguard users for wg01
  vyos.vyos.vyos_config:
    lines:
    - set interfaces wireguard wg01 peer TestTunnel allowed-ips 172.31.0.2/32
    - set interfaces wireguard wg01 peer TestTunnel pubkey xxxxxxxxx

TO (example)
- name: setup wg01
  vyos.vyos.vyos_interfaces:
    config:
    - name: wg01
      description: Configured by Ansible
      enabled: true
      port: 51820
      address: 172.31.0.1/24
      peer:
        - name: TestTunnel
          allowed_ips: 172.31.0.2/32
          pubkey: xxxxxxxxx
```

### PR DESCRIPTION
**Pull request by GomathiselviS**
##### SUMMARY

Depends-On: https://github.com/ansible-collections/vyos.vyos/pull/140

Partially fixes #133 

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by rohitthakur2590** [comment]
@GomathiselviS This looks good and are we also planning to support complete wiregaurd configuration.
like peer, port etc?

**Review by rohitthakur2590 — COMMENTED** [review]
have we tested the fact-gathering for this ?

**Comment by GomathiselviS** [comment]
> have we tested the fact-gathering for this ?

@rohitthakur2590  I have added the test.

**Comment by GomathiselviS** [comment]
> @GomathiselviS This looks good and are we also planning to support complete wiregaurd configuration.
> like peer, port etc?

@rohitthakur2590 Yes, in a separate PR, in the April Month release.

**Comment by GomathiselviS** [comment]
recheck

**Pull request merged**
