### PR TITLE
tests: remove unintended .swp file

### PR DESCRIPTION
**Pull request by dmsimard**
##### SUMMARY
Depends-On: https://github.com/ansible-collections/vyos.vyos/pull/220
.swp files are VI temporary files and it was likely not intended to be
added to the repository.

##### ISSUE TYPE
- Bugfix Pull Request
- 
##### COMPONENT NAME
tests

### CODE REVIEW

**Comment by GomathiselviS** [comment]
@dmsimard Thanks for working on this. Can you please add a changelog fragment?

**Comment by dmsimard** [comment]
> @dmsimard Thanks for working on this. Can you please add a changelog fragment?

@GomathiselviS is it really necessary ? This removes an unused file that was added by mistake.

**Comment by GomathiselviS** [comment]
> > @dmsimard Thanks for working on this. Can you please add a changelog fragment?
> 
> @GomathiselviS is it really necessary ? This removes an unused file that was added by mistake.

@dmsimard Yes. For now, any changes made under plugins and tests directory require a changelog. Otherwise , ` ansible-changelog-fragment  `  test fails.

**Comment by GomathiselviS** [comment]
recheck

**Review by GomathiselviS — APPROVED** [review]

**Pull request merged**
