### PR TITLE
Spelling glitch fix on doc

### PR DESCRIPTION
**Pull request by KB-perByte**
##### SUMMARY

Spelling glitch fix on doc

##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by KB-perByte** [comment]
recheck

**Review by ashwini-mhatre — APPROVED** [review]

**Comment by KB-perByte** [comment]
recheck

**Comment by KB-perByte** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Pull request merged**
