### PR TITLE
Prevent vyos_config from saving in check mode.

### PR DESCRIPTION
**Pull request by AngusWarren**
##### SUMMARY
This PR prevents configuration from being saved while running in check mode. This aligns vyos_config's behaviour with other _config modules and with the intention of Ansible's check mode.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
vyos_config

##### ADDITIONAL INFORMATION
Examples of other _command modules which avoid saving in check mode. 
https://github.com/ansible-collections/arista.eos/blob/master/plugins/modules/eos_config.py
https://github.com/ansible-collections/cisco.asa/blob/master/plugins/modules/asa_config.py
https://github.com/ansible-collections/cisco.ios/blob/master/plugins/modules/ios_config.py

### CODE REVIEW

**Comment by pabelanger** [comment]
Thanks for the PR, but there is something wrong if your patch. For some reasons, more then 350lines were touched in your change. Can you check why that is, and only modify the code you need to update?

**Comment by AngusWarren** [comment]
Sorry, I should have picked that up before submitting. It looks like there was an issue with the line ending in my original PR.

**Comment by rohitthakur2590** [comment]
recheck

**Comment by AngusWarren** [comment]
> @AngusWarren as I could see we have already decided the commit operation based on check-mode. could you explain why we need below check when we won't be having any save operation?

Hi @rohitthakur2590, that line prevents vyos_config from commiting new changes to the active configuration. The problem is that if there are preexisting unsaved changes on the device, vyos_config will save them to persistent storage without testing for check mode.

This line is responsible for the save action:
https://github.com/ansible-collections/vyos.vyos/blob/71fbaa67d8150d2e8d51a104089991524535d93c/plugins/modules/vyos_config.py#L343

**Comment by rohitthakur2590** [comment]
> > @AngusWarren as I could see we have already decided the commit operation based on check-mode. could you explain why we need below check when we won't be having any save operation?
> 
> Hi @rohitthakur2590, that line prevents vyos_config from commiting new changes to the active configuration. The problem is that if there are preexisting unsaved changes on the device, vyos_config will save them to persistent storage without testing for check mode.
> 
> This line is responsible for the save action:
> https://github.com/ansible-collections/vyos.vyos/blob/71fbaa67d8150d2e8d51a104089991524535d93c/plugins/modules/vyos_config.py#L343

@AngusWarren  Ah !  "save = true" in check mode wasn't idempotent. This LGTM! Thanks

**Comment by AngusWarren** [comment]
recheck

**Comment by AngusWarren** [comment]
recheck

**Comment by AngusWarren** [comment]
recheck

**Comment by AngusWarren** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
