### PR TITLE
[vyos] Provide feedback on linters failure

### PR DESCRIPTION
**Pull request by GomathiselviS**
To provide actionable feedback for formatting failures.

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Pull request merged**
