### PR TITLE
Fix `pre-commit` Issues

### PR DESCRIPTION
**Pull request by sdwilsh**
##### SUMMARY
This change fixes `.pre-commit-config.yaml` so that `main` no longer has errors on it.  To accomplish that, two things had to be done:
* Update the version of `black` that `pre-commit` uses to match what `tox` uses.
* Run `pre-commit run --all-files` and commit the results

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below
$ pre-commit run --all-files
Check for merge conflicts................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Debug Statements (Python)................................................Passed
Fix End of Files.........................................................Passed
Don't commit to branch...................................................Passed
Trim Trailing Whitespace.................................................Passed
black....................................................................Passed
Update documentation.....................................................Passed
```

### CODE REVIEW

**Comment by sdwilsh** [comment]
@ashwini-mhatre or @GomathiselviS, any chance we could get this reviewed soon?

**Comment by GomathiselviS** [comment]
recheck

**Review by Qalthos — APPROVED** [review]

**Comment by sdwilsh** [comment]
Thanks for helping to push this forward, @Qalthos!

**Comment by Qalthos** [comment]
Sorry this took so long to get done. pre-commit.ci is now enabled on the repo as well, so this hopefully shouldn't be a problem in the future either.

**Pull request merged**
