### PR TITLE
git ls-files -z -- .pre-commit-config.yaml | xargs -0 sed -i 's/0.9.[12]/0.9.3/'

### PR DESCRIPTION
**Pull request by Qalthos**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1101
Committed via https://github.com/asottile/all-repos

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by pabelanger** [comment]
going to test skipping of testing on this file

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
