### PR TITLE
Replace meta/main.yaml support with include_role

### PR DESCRIPTION
**Pull request by pabelanger**
meta/main.yaml is the old way of doing things, and in our case doesn't
work in network-ee jobs.  We can instead use include_role to ensure the
role runs.

Depends-On: https://github.com/ansible/network-ee/pull/135
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by NilashishC** [comment]
Closing this since this collection has been deprecated as this PR also seems to have many merge conflicts now.

**Pull request closed without merging**
