### PR TITLE
[firewall_global] port-groups are not added

### LINKED ISSUE #107: Firewall global port-groups are not added
##### SUMMARY
Adding port groups are not handled.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
plugins/module_utils/network/vyos/config/firewall_global/firewall_global.py

##### ANSIBLE VERSION

```
ansible 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

----

I deleted the rest, because a PR is incoming. This is due to a typo when a - was used instead of an underscore.

```
diff --git a/plugins/module_utils/network/vyos/config/firewall_global/firewall_global.py b/plugins/module_utils/network/vyos/config/firewall_global/firewall_global.py
index 08b724a..3d61df7 100644
--- a/plugins/module_utils/network/vyos/config/firewall_global/firewall_global.py
+++ b/plugins/module_utils/network/vyos/config/firewall_global/firewall_global.py
@@ -349,7 +349,7 @@ class Firewall_global(ConfigBase):
                 h_grp = h.get("group") or {}
             if w:
                 commands.extend(
-                    self._render_grp_mem("port-group", w["group"], h_grp, opr)
+                    self._render_grp_mem("port_group", w["group"], h_grp, opr)
                 )
                 commands.extend(
                     self._render_grp_mem(
```

### PR DESCRIPTION
**Pull request by sdwilsh**
Fixes #107
Supersedes #108

### CODE REVIEW

**Comment by sdwilsh** [comment]
I haven't figured out how to run tests locally yet, but xuul will tell me if I guessed correctly, I suppose.

**Comment by sdwilsh** [comment]
The error with python37 looks to be a host configuration issue (`git` is not installed?), and I don't see why the tests would operate differently on 3.7.  I think this is ready for review.

**Comment by Qalthos** [comment]
recheck

**Comment by sdwilsh** [comment]
@GomathiselviS ping for review

**Comment by sdwilsh** [comment]
The only thing I'm doing with these force pushes is rebasing.  None of the failures appear to be related at all to the changes in this pull request.

**Comment by sdwilsh** [comment]
The failure looks to be a `black` formatting issue in a file I'm not changing.

**Comment by GomathiselviS** [comment]
@sdwilsh Execute `tox -eblack` and `tox -elinters` from vyos/vyos. This will help you fix the formatting issues. You can work on the errors thrown by these commands and push the committed changes.

**Comment by sdwilsh** [comment]
The linting issue would have been fixed with #154, but instead got fixed in e1c29bf3b6e0ba4887693fcc347d8887051aa148.  I'll rebase again.

**Review by GomathiselviS — APPROVED** [review]

**Pull request merged**
