### PR TITLE
Enable configuring new interface which is not present in the config

### PR DESCRIPTION
**Pull request by GomathiselviS**
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>
Depends-On: https://github.com/ansible-collections/vyos.vyos/pull/104
##### SUMMARY

Fixes: https://github.com/ansible-collections/vyos.vyos/issues/91

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

vyos_interfaces.py

##### ADDITIONAL INFORMATION

"enabled" key is copied along with "name" key, to "have" from "want", when "have" does not have the interface.

```paste below

```

### CODE REVIEW

**Comment by rohitthakur2590** [comment]
@GomathiselviS 
https://github.com/ansible-collections/vyos.vyos/blob/0cfc69abca0979f963948e3192b713e385bf195f/plugins/module_utils/network/vyos/config/interfaces/interfaces.py#L231
This needs to be updated where have_copy is None , you can have something like : 
```
        if have_copy:
            have_vifs = have_copy.pop("vifs", [])
            updates = dict_diff(have_copy, want_copy)
        else:
            updates = want_copy
```

**Comment by rohitthakur2590** [comment]
@GomathiselviS  This might result in the wrong command when 'key' is just 'name'
https://github.com/ansible-https://github.com/ansible-collections/vyos.vyos/blob/0cfc69abca0979f963948e3192b713e385bf195f/plugins/module_utils/network/vyos/config/interfaces/interfaces.py#L350

**Review by rohitthakur2590 — CHANGES_REQUESTED** [review]
added few minor comments

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
> @GomathiselviS This might result in the wrong command when 'key' is just 'name'
> https://github.com/ansible-https://github.com/ansible-collections/vyos.vyos/blob/0cfc69abca0979f963948e3192b713e385bf195f/plugins/module_utils/network/vyos/config/interfaces/interfaces.py#L350

@rohitthakur2590 As discussed, 'delete ... disable' commands can be removed. So this line will not be affected.

**Review by rohitthakur2590 — APPROVED** [review]

**Pull request merged**
